/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.extras.FlatSVGIcon;

/**
 *
 * @author DellU
 */
public class DangNhapFrm extends javax.swing.JFrame {
    private javax.swing.border.Border defaultBorder;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DangNhapFrm.class.getName());

    /**
     * Creates new form DangNhapFrm
     */
    public DangNhapFrm() {
        initComponents();  
        btnSignIn.addActionListener(this::btnSignInActionPerformed);
        btnReturn.addActionListener(this::btnReturnActionPerformed);
        btnGoogleAcc.setIcon(new FlatSVGIcon("svgmaterials/icons/bxl-google.svg", 24, 24));
        btnFacebookAcc.setIcon(new FlatSVGIcon("svgmaterials/icons/bxl-facebook.svg", 24, 24));
 
        btnGoogleAcc.setIconTextGap(10);
        btnFacebookAcc.setIconTextGap(10);  

        this.setLocationRelativeTo(null); 
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 

        PasswordField1.setText(""); 
        PasswordField1.putClientProperty("JTextField.placeholderText", "Nhập mật khẩu..."); 
        NameAccount.putClientProperty("JTextField.placeholderText", "Nhập Username...");

        defaultBorder = NameAccount.getBorder();

        NameAccount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) thucHienDangNhap();
            }
        });

        PasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) thucHienDangNhap();
            }
        }); 

        this.setLayout(new java.awt.BorderLayout()); 
        this.add(LoginLable, java.awt.BorderLayout.CENTER); 
        this.pack(); 
        this.setResizable(false); 
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginLable = new gui.custom.RoundedPanel();
        LablePassword = new javax.swing.JLabel();
        btnGoogleAcc = new javax.swing.JButton();
        btnFacebookAcc = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        LableTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NameAccount = new javax.swing.JTextField();
        PasswordField1 = new javax.swing.JPasswordField();
        btnSignIn = new javax.swing.JButton();
        rbtnRemember = new javax.swing.JRadioButton();
        lblErrorPass = new javax.swing.JLabel();
        lblErrorUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginLable.setBackground(new java.awt.Color(255, 255, 255));

        LablePassword.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        LablePassword.setText("Password:");

        btnGoogleAcc.setBackground(new java.awt.Color(204, 204, 204));
        btnGoogleAcc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGoogleAcc.setText("Google");
        btnGoogleAcc.addActionListener(this::btnGoogleAccActionPerformed);

        btnFacebookAcc.setBackground(new java.awt.Color(204, 204, 204));
        btnFacebookAcc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFacebookAcc.setText("Facebook");
        btnFacebookAcc.addActionListener(this::btnFacebookAccActionPerformed);

        btnReturn.setText("Quay lại\n");
        btnConfirm.addActionListener(this::btnConfirmActionPerformed);
        btnConfirm.setBackground(new java.awt.Color(255, 255, 51));
        btnConfirm.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnConfirm.setText("Nhập");

        LableTitle.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        LableTitle.setForeground(new java.awt.Color(255, 0, 0));
        LableTitle.setText("ĐĂNG NHẬP TÀI KHOẢN");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setText("Username:");

        NameAccount.addActionListener(this::NameAccountActionPerformed);

        PasswordField1.setText("jPasswordField1");

        btnSignIn.setText("Đăng ký");

        rbtnRemember.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        rbtnRemember.setText("Ghi nhớ tài khoản");

        lblErrorPass.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lblErrorPass.setForeground(new java.awt.Color(255, 0, 51));

        lblErrorUser.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lblErrorUser.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout LoginLableLayout = new javax.swing.GroupLayout(LoginLable);
        LoginLable.setLayout(LoginLableLayout);
        LoginLableLayout.setHorizontalGroup(
            LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLableLayout.createSequentialGroup()
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLableLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(LableTitle))
                    .addGroup(LoginLableLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(LoginLableLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(rbtnRemember)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LoginLableLayout.createSequentialGroup()
                                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGoogleAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFacebookAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLableLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LablePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NameAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLableLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblErrorUser)
                    .addComponent(lblErrorPass))
                .addGap(124, 124, 124))
        );
        LoginLableLayout.setVerticalGroup(
            LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLableLayout.createSequentialGroup()
                .addComponent(LableTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLableLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(NameAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLableLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LablePassword)
                    .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnRemember))
                .addGap(18, 18, 18)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFacebookAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoogleAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(LoginLable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginLable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(374, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameAccountActionPerformed

    private void btnFacebookAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacebookAccActionPerformed
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://www.facebook.com/login/"));
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnFacebookAccActionPerformed

    private void btnGoogleAccActionPerformed(java.awt.event.ActionEvent evt) {                                             
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://accounts.google.com/"));
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }                                              

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {                                                                                                                                                                           
        this.dispose();  
    }                                             

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {                                                                                                                                                                         
        DangKyFrm frm = new DangKyFrm();
        frm.setLocationRelativeTo(null); 
        frm.setVisible(true);
        this.dispose();

    }                                          

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        thucHienDangNhap();
    }//GEN-LAST:event_btnConfirmActionPerformed
    private void thucHienDangNhap() {
        NameAccount.setBorder(defaultBorder);
        PasswordField1.setBorder(defaultBorder);
        lblErrorUser.setText(" ");
        lblErrorPass.setText(" ");

        String user = NameAccount.getText().trim();
        String pass = new String(PasswordField1.getPassword());

        boolean hasError = false;

        if (user.isEmpty()) {
            NameAccount.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));
            lblErrorUser.setText("* Chưa nhập tên tài khoản");
            hasError = true;
        }
        if (pass.isEmpty()) {
            PasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));
            lblErrorPass.setText("* Chưa nhập mật khẩu");
            hasError = true;
        }

        if (hasError) return;

        bll.NguoiDungBUS bus = new bll.NguoiDungBUS();
        model.NguoiDung nd = bus.checkLogin(user, pass);

        if (nd != null) { 
            if (rbtnRemember.isSelected()) {
                java.util.prefs.Preferences prefs = java.util.prefs.Preferences.userNodeForPackage(DangNhapFrm.class);
                prefs.put("saved_user", user);
                prefs.put("saved_pass", pass);
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Đăng nhập thành công!\nXin chào: " + nd.getUsername(), "Thông báo", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
            for (java.awt.Window window : java.awt.Window.getWindows()) {
                window.dispose();
            }
            
            new MainFrame(nd).setVisible(true);
             
        } else {
            NameAccount.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));
            PasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));
            lblErrorPass.setText("* Sai tên đăng nhập hoặc mật khẩu");
            PasswordField1.setText("");
            NameAccount.requestFocus();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DangNhapFrm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LablePassword;
    private javax.swing.JLabel LableTitle;
    private javax.swing.JPanel LoginLable;
    private javax.swing.JTextField NameAccount;
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnFacebookAcc;
    private javax.swing.JButton btnGoogleAcc;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblErrorPass;
    private javax.swing.JLabel lblErrorUser;
    private javax.swing.JRadioButton rbtnRemember;
    // End of variables declaration//GEN-END:variables
}