/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author DellU
 */
public class DangKyFrm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DangKyFrm.class.getName());
    private int passStrength = 0; 
    private javax.swing.border.Border defaultBorder;
    /**
     * Creates new form DangKyFrm
     */
    public DangKyFrm() {
        initComponents();  
        java.awt.Color PRIMARY_COLOR = new java.awt.Color(18, 32, 64);
    java.awt.Color SECONDARY_COLOR = new java.awt.Color(45, 72, 140);
    java.awt.Color SUCCESS_COLOR = new java.awt.Color(76, 175, 80);
    java.awt.Color DANGER_COLOR = new java.awt.Color(244, 67, 54);
    java.awt.Color BG_MAIN = new java.awt.Color(245, 247, 250); 

    this.getContentPane().setBackground(BG_MAIN);
    LoginLable.setBackground(java.awt.Color.WHITE);

    LableTitle.setForeground(PRIMARY_COLOR);

    btnConfirm.setBackground(SUCCESS_COLOR);
    btnConfirm.setForeground(java.awt.Color.WHITE);

    btnReturn.setBackground(SECONDARY_COLOR);
    btnReturn.setForeground(java.awt.Color.WHITE);

    btnExit.setBackground(DANGER_COLOR);
    btnExit.setForeground(java.awt.Color.WHITE);
        defaultBorder = NameAccount.getBorder();
        lbErrorUsNa.setText(" ");
        lbErrorName.setText(" ");
        lbErrorPass.setText(" ");
        lbErrorConPass.setText(" ");
        this.setLayout(new java.awt.BorderLayout()); 
        this.add(LoginLable, java.awt.BorderLayout.CENTER); 
        this.pack(); 
        this.setResizable(false); 
        this.setLocationRelativeTo(null); 
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 

        PasswordField.setText("");
        confirmPass.setText("");
        NameAccount.putClientProperty("JTextField.placeholderText", "Viết liền, không dấu cách..."); 

        btnSeePass.setText("👁"); 
        btnSeeCnPass.setText("👁"); 

        btnSeePass.addActionListener(e -> togglePassword(PasswordField, btnSeePass));
        btnSeeCnPass.addActionListener(e -> togglePassword(confirmPass, btnSeeCnPass));
        
        btnExit.addActionListener(e -> {
            new MainFrame().setVisible(true); 
            this.dispose();
        });
        
        btnReturn.addActionListener(e -> {
            DangNhapFrm frm = new DangNhapFrm();
            frm.setLocationRelativeTo(null);
            frm.setVisible(true);
            this.dispose(); 
        });
        
        btnConfirm.addActionListener(e -> thucHienDangKy()); 

        PasswordField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { checkPassword(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { checkPassword(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { checkPassword(); }
        });
        
        confirmPass.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { checkConfirmPassword(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { checkConfirmPassword(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { checkConfirmPassword(); }
        });

        NameAccount.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { clearUserError(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { clearUserError(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { clearUserError(); }
        });

        NameUser.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { clearNameError(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { clearNameError(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { clearNameError(); }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginLable = new gui.custom.RoundedPanel();
        NameAccount = new javax.swing.JTextField();
        LableUsername = new javax.swing.JLabel();
        LablePassword = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        LableTitle = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        confirmPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        NameUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSeePass = new javax.swing.JButton();
        btnSeeCnPass = new javax.swing.JButton();
        lbErrorUsNa = new javax.swing.JLabel();
        lbErrorName = new javax.swing.JLabel();
        lbErrorPass = new javax.swing.JLabel();
        lbErrorConPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginLable.setBackground(new java.awt.Color(255, 255, 255));

        NameAccount.addActionListener(this::NameAccountActionPerformed);

        LableUsername.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        LableUsername.setText("Họ và tên:");

        LablePassword.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        LablePassword.setText("Password:");

        btnReturn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReturn.setText("Quay lại\n");

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit.setText("Thoát");
        btnExit.addActionListener(this::btnExitActionPerformed);

        btnConfirm.setBackground(new java.awt.Color(255, 255, 51));
        btnConfirm.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnConfirm.setText("Xác nhận");

        LableTitle.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        LableTitle.setForeground(new java.awt.Color(255, 0, 0));
        LableTitle.setText("ĐĂNG KÝ TÀI KHOẢN ");

        PasswordField.setText("jPasswordField1");

        confirmPass.setText("jPasswordField1");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setText("Username:");

        NameUser.addActionListener(this::NameUserActionPerformed);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Xác nhận password:");

        btnSeePass.setText("jButton1");

        btnSeeCnPass.setText("jButton1");

        lbErrorUsNa.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lbErrorUsNa.setForeground(new java.awt.Color(255, 0, 51));
        lbErrorUsNa.setText("jLabel3");

        lbErrorName.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lbErrorName.setForeground(new java.awt.Color(255, 0, 51));
        lbErrorName.setText("jLabel3");

        lbErrorPass.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lbErrorPass.setForeground(new java.awt.Color(255, 0, 51));
        lbErrorPass.setText("jLabel3");

        lbErrorConPass.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lbErrorConPass.setForeground(new java.awt.Color(255, 0, 51));
        lbErrorConPass.setText("jLabel3");

        javax.swing.GroupLayout LoginLableLayout = new javax.swing.GroupLayout(LoginLable);
        LoginLable.setLayout(LoginLableLayout);
        LoginLableLayout.setHorizontalGroup(
            LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLableLayout.createSequentialGroup()
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLableLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginLableLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLableLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLableLayout.createSequentialGroup()
                        .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LableTitle)
                            .addGroup(LoginLableLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(LableUsername)
                                    .addComponent(LablePassword)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NameAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(LoginLableLayout.createSequentialGroup()
                                        .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(confirmPass, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                            .addComponent(PasswordField))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSeeCnPass, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSeePass, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLableLayout.createSequentialGroup()
                        .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbErrorName)
                            .addComponent(lbErrorUsNa)
                            .addComponent(lbErrorPass)
                            .addComponent(lbErrorConPass))
                        .addGap(145, 145, 145))))
        );
        LoginLableLayout.setVerticalGroup(
            LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLableLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(LableTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NameAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbErrorUsNa)
                .addGap(10, 10, 10)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LableUsername)
                    .addComponent(NameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(lbErrorName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LablePassword)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeePass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbErrorPass)
                .addGap(12, 12, 12)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnSeeCnPass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbErrorConPass)
                .addGap(12, 12, 12)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturn)
                    .addComponent(btnExit))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(LoginLable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LoginLable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameAccountActionPerformed

    private void NameUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameUserActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                        

    private void togglePassword(javax.swing.JPasswordField pf, javax.swing.JButton btn) {
        if (pf.getEchoChar() != (char) 0) {
            pf.setEchoChar((char) 0);
            btn.setText("🙈");
        } else {
            pf.setEchoChar('•');
            btn.setText("👁");
        }
    } 

    private void clearUserError() {
        NameAccount.setBorder(defaultBorder);
        lbErrorUsNa.setText(" ");
    }

    private void clearNameError() {
        NameUser.setBorder(defaultBorder);
        lbErrorName.setText(" ");
    }

    private void checkConfirmPassword() {
        String p = new String(PasswordField.getPassword());
        String cP = new String(confirmPass.getPassword());
        if (cP.isEmpty()) {
            confirmPass.setBorder(defaultBorder);
            lbErrorConPass.setText(" ");
        } else if (!p.equals(cP)) {
            confirmPass.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));
            lbErrorConPass.setText("* Xác nhận mật khẩu không khớp");
        } else {
            confirmPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51), 2)); 
            lbErrorConPass.setText(" ");
        }
    }

    private void checkPassword() {
        String p = new String(PasswordField.getPassword());
        passStrength = 0;
        
        if (p.length() > 0) passStrength++; 
        if (p.length() >= 6) passStrength++; 
        if (p.matches(".*[a-z].*") && p.matches(".*[A-Z].*")) passStrength++; 
        if (p.matches(".*\\d.*")) passStrength++; 
        if (p.matches(".*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?].*")) passStrength++; 
        if (p.length() >= 8 && passStrength == 5) passStrength++; 
        
        LablePassword.setText("Password:");
        
        if (p.isEmpty()) {
            PasswordField.setBorder(defaultBorder);
            lbErrorPass.setText(" ");
        } else if (passStrength < 3) {
            PasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));
            lbErrorPass.setText("* Mật khẩu quá yếu (Cần chữ hoa, số, ký tự đ.biệt)");
        } else {
            PasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51), 2)); 
            lbErrorPass.setText(" ");
        }
        
        checkConfirmPassword(); 
    }
    
    private void thucHienDangKy() {
        String user = NameAccount.getText().trim();
        String fullName = NameUser.getText().trim(); 
        String pass = new String(PasswordField.getPassword());
        String cPass = new String(confirmPass.getPassword());
        
        boolean hasError = false;

        if (user.isEmpty()) {
            NameAccount.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));
            lbErrorUsNa.setText("* Chưa nhập Username");
            hasError = true;
        } else if (user.contains(" ")) {
            NameAccount.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));
            lbErrorUsNa.setText("* Username không được chứa khoảng trắng");
            hasError = true;
        }

        if (fullName.isEmpty()) {
            NameUser.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));
            lbErrorName.setText("* Chưa nhập Họ và tên");
            hasError = true;
        }

        if (pass.isEmpty()) {
            PasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));
            lbErrorPass.setText("* Chưa nhập mật khẩu");
            hasError = true;
        } else if (passStrength < 3) {
            hasError = true; 
        }

        if (cPass.isEmpty()) {
            confirmPass.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));
            lbErrorConPass.setText("* Chưa nhập xác nhận mật khẩu");
            hasError = true;
        } else if (!pass.equals(cPass)) {
            hasError = true; 
        }

        if (hasError) return; 
        
        long randomID = System.currentTimeMillis() % 100000;
        String maND = "ND" + randomID; 
        
        bll.NguoiDungBUS bus = new bll.NguoiDungBUS();
        model.NguoiDung ndNew = new model.NguoiDung(maND, user, pass, "", "", java.time.LocalDate.now(), "KhachHang", "HoatDong");
        
        String result = bus.themNguoiDung(ndNew);
        
        if (result.contains("thành công")) {
            try {
                dal.ThongTinHanhKhachDAO tthkDao = new dal.ThongTinHanhKhachDAO();
                model.ThongTinHanhKhach hkNew = new model.ThongTinHanhKhach();
                hkNew.setMaHK("HK" + randomID);
                hkNew.setMaNguoiDung(maND);
                hkNew.setHoTen(fullName);
                hkNew.setMaThuHang(""); 
                hkNew.setCccd("");
                hkNew.setHoChieu("");
                hkNew.setNgaySinh(java.time.LocalDate.of(2000, 1, 1)); 
                hkNew.setGioiTinh("Chưa cập nhật");
                hkNew.setDiemTichLuy(0);
                tthkDao.insert(hkNew); 
            } catch (Exception ex) {}

            javax.swing.JOptionPane.showMessageDialog(this, "Tạo tài khoản thành công!\nChào mừng " + fullName + " đến với AirLiner.", "Thành công", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            DangNhapFrm frm = new DangNhapFrm();
            frm.setLocationRelativeTo(null);
            frm.setVisible(true);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Đăng ký thất bại!\nLý do: " + result + "\n(Có thể Username này đã có người sử dụng)", "Lỗi Database", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DangKyFrm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LablePassword;
    private javax.swing.JLabel LableTitle;
    private javax.swing.JLabel LableUsername;
    private javax.swing.JPanel LoginLable;
    private javax.swing.JTextField NameAccount;
    private javax.swing.JTextField NameUser;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSeeCnPass;
    private javax.swing.JButton btnSeePass;
    private javax.swing.JPasswordField confirmPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbErrorConPass;
    private javax.swing.JLabel lbErrorName;
    private javax.swing.JLabel lbErrorPass;
    private javax.swing.JLabel lbErrorUsNa;
    // End of variables declaration//GEN-END:variables
}
