/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui; 

import com.formdev.flatlaf.extras.FlatSVGIcon;
/**
 *
 * @author DellU
 */
public class DangNhapFrm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DangNhapFrm.class.getName());

    /**
     * Creates new form DangNhapFrm
     */
    public DangNhapFrm() {
        initComponents(); 
        btnGoogleAcc.setIcon(new FlatSVGIcon("svgmaterials/icons/bxl-google.svg", 24, 24)); 
        btnFacebookAcc.setIcon(new FlatSVGIcon("svgmaterials/icons/bxl-facebook.svg", 24, 24));  
 
        btnGoogleAcc.setIconTextGap(10);
        btnFacebookAcc.setIconTextGap(10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginLable = new gui.custom.RoundedPanel();
        Username = new javax.swing.JTextField();
        LableUsername = new javax.swing.JLabel();
        LablePassword = new javax.swing.JLabel();
        btnGoogleAcc = new javax.swing.JButton();
        btnFacebookAcc = new javax.swing.JButton();
        rBtnRemember = new javax.swing.JRadioButton();
        btnReturn = new javax.swing.JButton();
        btnSignIn = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        LableTitle = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginLable.setBackground(new java.awt.Color(255, 255, 255));

        Username.addActionListener(this::UsernameActionPerformed);

        LableUsername.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        LableUsername.setText("Username: ");

        LablePassword.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        LablePassword.setText("Password:");

        btnGoogleAcc.setBackground(new java.awt.Color(204, 204, 204));
        btnGoogleAcc.setText("Google");
        btnGoogleAcc.addActionListener(this::btnGoogleAccActionPerformed);

        btnFacebookAcc.setBackground(new java.awt.Color(204, 204, 204));
        btnFacebookAcc.setText("Facebook");
        btnFacebookAcc.addActionListener(this::btnFacebookAccActionPerformed);

        rBtnRemember.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        rBtnRemember.setText("Ghi nhớ mật khẩu");
        rBtnRemember.addActionListener(this::rBtnRememberActionPerformed);

        btnReturn.setText("Quay lại\n");

        btnSignIn.setText("Đăng ký");

        btnConfirm.setBackground(new java.awt.Color(255, 255, 51));
        btnConfirm.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnConfirm.setText("Nhập\n");

        LableTitle.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        LableTitle.setForeground(new java.awt.Color(255, 0, 0));
        LableTitle.setText("ĐĂNG NHẬP TÀI KHOẢN ");

        PasswordField.setText("jPasswordField1");

        javax.swing.GroupLayout LoginLableLayout = new javax.swing.GroupLayout(LoginLable);
        LoginLable.setLayout(LoginLableLayout);
        LoginLableLayout.setHorizontalGroup(
            LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLableLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLableLayout.createSequentialGroup()
                        .addComponent(LableTitle)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLableLayout.createSequentialGroup()
                        .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(LoginLableLayout.createSequentialGroup()
                                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rBtnRemember)
                                    .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnSignIn)
                                        .addComponent(btnGoogleAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(LoginLableLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnReturn)
                                            .addComponent(btnFacebookAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(LoginLableLayout.createSequentialGroup()
                                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LablePassword)
                                    .addComponent(LableUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Username, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(PasswordField))))
                        .addGap(158, 158, 158))))
        );
        LoginLableLayout.setVerticalGroup(
            LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLableLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LableTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LableUsername)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LablePassword)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnRemember)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGoogleAcc)
                    .addComponent(btnFacebookAcc))
                .addGap(80, 80, 80)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturn)
                    .addComponent(btnSignIn))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(LoginLable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LoginLable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void rBtnRememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnRememberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnRememberActionPerformed

    private void btnGoogleAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoogleAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoogleAccActionPerformed

    private void btnFacebookAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacebookAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacebookAccActionPerformed
    
    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {                                           
    String user = Username.getText();
    String pass = new String(PasswordField.getPassword()); 

    bus.NguoiDungBUS bus = new bus.NguoiDungBUS();
    model.NguoiDung nd = bus.checkLogin(user, pass);

    if (nd != null) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Đăng nhập thành công!\nXin chào: " + nd.getUsername(), 
            "Thông báo", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        new MainFrame(nd).setVisible(true);
        this.dispose(); 
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Sai tên đăng nhập hoặc mật khẩu!", 
            "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
            
        PasswordField.setText("");
        Username.requestFocus(); 
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DangNhapFrm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LablePassword;
    private javax.swing.JLabel LableTitle;
    private javax.swing.JLabel LableUsername;
    private javax.swing.JPanel LoginLable;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField Username;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnFacebookAcc;
    private javax.swing.JButton btnGoogleAcc;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JRadioButton rBtnRemember;
    // End of variables declaration//GEN-END:variables
}
