/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author DellU
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    
    /**
     * Creates new form LichBayFrm
     */
    public MainFrame() {
        initComponents();    
        setupLogo(); 
        applyTheme();
        gui.custom.UIHelper.loadSanBayToComboBox(cbCities, cbCities1);
        setupCurrencyComboBox(); 
        setupHanhKhachPopup();  
        setupDatePicker(jFormattedTextField1); 
        setupDatePicker(jFormattedTextField2);
        setupBusinessLogic();  
        
        
        jButton2.setText(""); 
        try {
       
            jButton2.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("svgmaterials/icons/bx-transfer.svg", 24, 24));
        } catch (Exception e) {
            System.out.println("Lỗi icon đổi chiều");
        } 
        for(java.awt.event.ActionListener al : btnLogin.getActionListeners()) btnLogin.removeActionListener(al);
        btnLogin.addActionListener(e -> {
            DangNhapFrm frm = new DangNhapFrm();
            frm.setLocationRelativeTo(this); 
            frm.setVisible(true);
       
        });
    } 


    private model.NguoiDung userHienTai;


    public MainFrame(model.NguoiDung nd) {
        initComponents();   
        applyTheme();
        setupLogo();
        gui.custom.UIHelper.loadSanBayToComboBox(cbCities, cbCities1);
        setupCurrencyComboBox(); 
        setupHanhKhachPopup(); 
        setupDatePicker(jFormattedTextField1); 
        setupDatePicker(jFormattedTextField2); 
        
    
        setupBusinessLogic();
        this.userHienTai = nd;
        setTitle("AirLiner - Xin chào: " + userHienTai.getUsername()); 
        
        btnSignin.setVisible(false);
        
        String chuCaiDau = "U";
        if (userHienTai.getUsername() != null && !userHienTai.getUsername().isEmpty()) {
            chuCaiDau = userHienTai.getUsername().substring(0, 1).toUpperCase();
        }
        
        java.awt.Color[] palette = {
            new java.awt.Color(234, 67, 53),
            new java.awt.Color(52, 168, 83),
            new java.awt.Color(66, 133, 244),
            new java.awt.Color(251, 188, 5),
            new java.awt.Color(156, 39, 176),
            new java.awt.Color(0, 150, 136),
            new java.awt.Color(255, 112, 67)
        };
        
        int randomIndex = new java.util.Random().nextInt(palette.length);
        
        btnLogin.setText(chuCaiDau); 
        btnLogin.setToolTipText("Hồ sơ của: " + userHienTai.getUsername()); 
        btnLogin.setBackground(palette[randomIndex]); 
        btnLogin.setForeground(java.awt.Color.WHITE); 
        btnLogin.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 22)); 
        btnLogin.putClientProperty("JButton.buttonType", "roundRect");
        
        javax.swing.JPopupMenu avatarMenu = new javax.swing.JPopupMenu();
        javax.swing.JMenuItem itemThongTin = new javax.swing.JMenuItem("Thông tin người dùng");
        javax.swing.JMenuItem itemLichSu = new javax.swing.JMenuItem("Lịch sử đặt vé");
        javax.swing.JMenuItem itemDangXuat = new javax.swing.JMenuItem("Đăng xuất");

        itemThongTin.addActionListener(e -> javax.swing.JOptionPane.showMessageDialog(this, "Đang xây dựng form Thông tin người dùng..."));
        itemLichSu.addActionListener(e -> javax.swing.JOptionPane.showMessageDialog(this, "Đang xây dựng form Lịch sử đặt vé..."));
        
        itemDangXuat.addActionListener(e -> {
            java.util.prefs.Preferences prefs = java.util.prefs.Preferences.userNodeForPackage(gui.DangNhapFrm.class);
            prefs.remove("saved_user");
            prefs.remove("saved_pass");
            
            new MainFrame().setVisible(true);
            this.dispose();
        });

        avatarMenu.add(itemThongTin);
        avatarMenu.add(itemLichSu);
        avatarMenu.addSeparator();
        avatarMenu.add(itemDangXuat);

        for(java.awt.event.ActionListener al : btnLogin.getActionListeners()) btnLogin.removeActionListener(al);
        btnLogin.addActionListener(e -> avatarMenu.show(btnLogin, 0, btnLogin.getHeight()));
        btnSignin.setVisible(false); 

        jButton2.setText(""); 
        try {
            jButton2.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("svgmaterials/icons/bx-transfer.svg", 24, 24));
        } catch (Exception e) {}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGChuyenBay = new javax.swing.ButtonGroup();
        pnlHeader = new javax.swing.JPanel();
        pnlContent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnVeMB = new javax.swing.JButton();
        btnDiary = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbCities = new javax.swing.JComboBox<>();
        cbCities1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        btnHanhKhach = new javax.swing.JButton();
        pnlMultiCities = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlMenuHeader = new javax.swing.JPanel();
        btnKhuyenMai = new javax.swing.JButton();
        btnDatCho = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnSignin = new javax.swing.JButton();
        cbDonViTienTe = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(255, 0, 51));
        getContentPane().add(pnlHeader, java.awt.BorderLayout.NORTH);

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));

        btnVeMB.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnVeMB.setText("Vé Máy Bay");
        btnVeMB.addActionListener(this::btnVeMBActionPerformed);

        btnDiary.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnDiary.setText("Cẩm Nang Du Lịch");
        btnDiary.addActionListener(this::btnDiaryActionPerformed);

        jButton1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton1.setText("Phiếu quà tặng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(btnVeMB)
                .addGap(37, 37, 37)
                .addComponent(btnDiary)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(600, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVeMB)
                    .addComponent(btnDiary)
                    .addComponent(jButton1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Từ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Đến");

        cbCities.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbCities.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn thành phố ", "Tp.HCM ", " ", " " }));

        cbCities1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbCities1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn thành phố ", "Tp.HCM ", "Hà Nội ", "Bangkok ", "Tokyo", " " }));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton2.setText("<=>");

        jRadioButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadioButton1.setText("một chiều / khứ hồi");
        jRadioButton1.addActionListener(this::jRadioButton1ActionPerformed);

        jRadioButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadioButton2.setText("Nhiều thành phố");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phổ thông ", "Phổ thông đặc biệt ", "Thương gia ", "Hạng nhất" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Ngày khởi hành");

        jFormattedTextField1.setText("12 th 2 2026");
        jFormattedTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jFormattedTextField1.addActionListener(this::jFormattedTextField1ActionPerformed);

        jFormattedTextField2.setText("15 th 2 2026");
        jFormattedTextField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jCheckBox1.setText("Khứ hồi");
        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);

        jButton3.setBackground(new java.awt.Color(255, 255, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Tìm kiếm");

        btnHanhKhach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHanhKhach.setText("1 Người lớn, 0 Trẻ em, 0 Em bé");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbCities1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCities, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnHanhKhach)
                        .addGap(20, 20, 20)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addComponent(jCheckBox1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHanhKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jCheckBox1))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCities, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCities1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlMultiCities.setMaximumSize(new java.awt.Dimension(250, 300));
        pnlMultiCities.setMinimumSize(new java.awt.Dimension(250, 300));
        pnlMultiCities.setPreferredSize(new java.awt.Dimension(1000, 50));
        pnlMultiCities.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout pnlMultiCitiesLayout = new javax.swing.GroupLayout(pnlMultiCities);
        pnlMultiCities.setLayout(pnlMultiCitiesLayout);
        pnlMultiCitiesLayout.setHorizontalGroup(
            pnlMultiCitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1357, Short.MAX_VALUE)
        );
        pnlMultiCitiesLayout.setVerticalGroup(
            pnlMultiCitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        pnlMenuHeader.setBackground(new java.awt.Color(255, 0, 51));

        btnKhuyenMai.setBackground(new java.awt.Color(255, 255, 0));
        btnKhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnKhuyenMai.setText("Khuyến mãi");

        btnDatCho.setBackground(new java.awt.Color(255, 255, 51));
        btnDatCho.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnDatCho.setText("Đặt chỗ của tôi");

        btnLogin.setBackground(new java.awt.Color(255, 255, 51));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnLogin.setText("Đăng nhập");

        btnSignin.setBackground(new java.awt.Color(255, 255, 51));
        btnSignin.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnSignin.setText("Đăng ký");
        btnSignin.setMaximumSize(new java.awt.Dimension(83, 33));
        btnSignin.setMinimumSize(new java.awt.Dimension(83, 33));
        btnSignin.addActionListener(this::btnSigninActionPerformed);

        cbDonViTienTe.setBackground(new java.awt.Color(255, 255, 51));
        cbDonViTienTe.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cbDonViTienTe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " VND | VI", " USD | EN" }));
        cbDonViTienTe.addActionListener(this::cbDonViTienTeActionPerformed);

        javax.swing.GroupLayout pnlMenuHeaderLayout = new javax.swing.GroupLayout(pnlMenuHeader);
        pnlMenuHeader.setLayout(pnlMenuHeaderLayout);
        pnlMenuHeaderLayout.setHorizontalGroup(
            pnlMenuHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuHeaderLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(cbDonViTienTe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKhuyenMai)
                .addGap(18, 18, 18)
                .addComponent(btnDatCho)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(btnSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlMenuHeaderLayout.setVerticalGroup(
            pnlMenuHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuHeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlMenuHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDonViTienTe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDatCho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSignin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("VNI-Franko", 0, 40)); // NOI18N
        jLabel1.setText("AirLiner");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 371, Short.MAX_VALUE)
                .addComponent(pnlMenuHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(430, 430, 430))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlMenuHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 540, Short.MAX_VALUE))
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlMultiCities, javax.swing.GroupLayout.DEFAULT_SIZE, 1357, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMultiCities, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pnlMultiCities.getAccessibleContext().setAccessibleName("");
        pnlMultiCities.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigninActionPerformed
        DangKyFrm frm = new DangKyFrm();
        frm.setLocationRelativeTo(this); 
        frm.setVisible(true);
    }//GEN-LAST:event_btnSigninActionPerformed

    private void cbDonViTienTeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDonViTienTeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDonViTienTeActionPerformed

    private void btnVeMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeMBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVeMBActionPerformed

    private void btnDiaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDiaryActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                   
    
    private void applyTheme() {
        java.awt.Color PRIMARY_COLOR = new java.awt.Color(18, 32, 64);
        java.awt.Color ACCENT_COLOR = new java.awt.Color(255, 193, 7);
        java.awt.Color BG_MAIN = new java.awt.Color(245, 247, 250);

        pnlHeader.setBackground(PRIMARY_COLOR);
        jPanel2.setBackground(PRIMARY_COLOR);
        pnlMenuHeader.setBackground(PRIMARY_COLOR);

        jLabel1.setForeground(java.awt.Color.WHITE);

        btnKhuyenMai.setBackground(PRIMARY_COLOR);
        btnKhuyenMai.setForeground(java.awt.Color.WHITE);
        btnKhuyenMai.setBorderPainted(false);

        btnDatCho.setBackground(PRIMARY_COLOR);
        btnDatCho.setForeground(java.awt.Color.WHITE);
        btnDatCho.setBorderPainted(false);

        btnLogin.setBackground(PRIMARY_COLOR);
        btnLogin.setForeground(java.awt.Color.WHITE);
        btnLogin.setBorderPainted(false);

        cbDonViTienTe.setBackground(PRIMARY_COLOR);
        cbDonViTienTe.setForeground(java.awt.Color.WHITE);

        btnSignin.setBackground(ACCENT_COLOR);
        btnSignin.setForeground(PRIMARY_COLOR);
        btnSignin.setBorderPainted(false);

        pnlContent.setBackground(BG_MAIN);

        jButton3.setBackground(ACCENT_COLOR);
        jButton3.setForeground(PRIMARY_COLOR);
    }

    private void setupCurrencyComboBox() {
        javax.swing.JComboBox rawCombo = cbDonViTienTe;
        rawCombo.removeAllItems();

        // Bạn giữ nguyên đường dẫn giống bên DangNhapFrm nhé
        rawCombo.addItem(new CurrencyItem("VND | VI", "svgmaterials/flags/1x1/vn.svg"));
        rawCombo.addItem(new CurrencyItem("USD | EN", "svgmaterials/flags/1x1/us.svg"));
        
        rawCombo.setRenderer(new javax.swing.DefaultListCellRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                // Ép kiểu về JLabel để xài chữ và hình
                javax.swing.JLabel label = (javax.swing.JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                
                if (value instanceof CurrencyItem) {
                    CurrencyItem item = (CurrencyItem) value;
                    label.setText(item.getText());
                    label.setIcon(item.getIcon()); // Lấy icon đã load sẵn từ trước ra xài
                    label.setIconTextGap(8); 
                }
                return label;
            }
        });
    }

    // Class quản lý Item: Load ảnh ngay từ lúc sinh ra
    class CurrencyItem {
        private String text;
        private javax.swing.Icon icon; // Lưu sẵn cái hình vào đây

        public CurrencyItem(String text, String iconPath) {
            this.text = text;
            try {
                // Tạo icon 1 lần duy nhất với kích thước 24x18
                com.formdev.flatlaf.extras.FlatSVGIcon svgIcon = new com.formdev.flatlaf.extras.FlatSVGIcon(iconPath, 24, 18);
                
                // Kiểm tra xem FlatLaf có thực sự tìm thấy và đọc được file SVG không
                if (svgIcon.hasFound()) {
                    this.icon = svgIcon;
                } else {
                    System.out.println("BÁO ĐỘNG ĐỎ: FlatLaf không tìm thấy file ảnh tại -> " + iconPath);
                    this.icon = null;
                }
            } catch (Exception e) {
                System.out.println("Lỗi tàng hình: " + e.getMessage());
                this.icon = null;
            }
        }

        public String getText() { return text; }
        public javax.swing.Icon getIcon() { return icon; }

        @Override 
        public String toString() { return text; } 
    }  

    private void setupHanhKhachPopup() {
     
        javax.swing.JPopupMenu popup = new javax.swing.JPopupMenu();

    
        javax.swing.JPanel pnl = new javax.swing.JPanel(new java.awt.GridLayout(3, 2, 10, 10));
        pnl.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

   
        javax.swing.JSpinner spnNL = new javax.swing.JSpinner(new javax.swing.SpinnerNumberModel(1, 1, 9, 1));
        javax.swing.JSpinner spnTE = new javax.swing.JSpinner(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));
        javax.swing.JSpinner spnEB = new javax.swing.JSpinner(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));

        pnl.add(new javax.swing.JLabel("Người lớn (>=12t):")); pnl.add(spnNL);
        pnl.add(new javax.swing.JLabel("Trẻ em (2-11t):")); pnl.add(spnTE);
        pnl.add(new javax.swing.JLabel("Em bé (<2t):")); pnl.add(spnEB);

        popup.add(pnl);


        javax.swing.event.ChangeListener updateText = e -> {
            btnHanhKhach.setText(spnNL.getValue() + " Người lớn, " + spnTE.getValue() + " Trẻ em, " + spnEB.getValue() + " Em bé");
        };

        spnNL.addChangeListener(updateText);
        spnTE.addChangeListener(updateText);
        spnEB.addChangeListener(updateText);
        btnHanhKhach.addActionListener(e -> {
            popup.show(btnHanhKhach, 0, btnHanhKhach.getHeight());
        });
    } 

    private java.time.LocalDate currentMonth = java.time.LocalDate.now();
    private java.time.format.DateTimeFormatter dateFormatter = java.time.format.DateTimeFormatter.ofPattern("dd / MM / yyyy");
    private java.util.List<javax.swing.JTextField> listNgayExtra = new java.util.ArrayList<>();
    private java.util.List<javax.swing.JButton> listBtnXoa = new java.util.ArrayList<>(); 
    private java.util.List<model.SanBay> danhSachSanBayGoc = new java.util.ArrayList<>();
    private boolean isUpdatingCombo = false; 
    private javax.swing.JButton btnSearchMulti;  
    private javax.swing.JButton btnMoreCities; 

    private void loadDanhSachSanBay() {
        danhSachSanBayGoc = new bll.SanBayBUS().getAllSanBay();
    }

    private void setupHoTroChonSanBay(javax.swing.JComboBox cbTu, javax.swing.JComboBox cbDen, javax.swing.JButton btnSwap) {
        // Lần đầu load full cho cả 2
        capNhatHaiComboBox(cbTu, cbDen, null, null);

        // Bắt sự kiện khi người dùng chọn 1 ô
        java.awt.event.ItemListener listener = e -> {
            if (isUpdatingCombo) return;
            if (e.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                model.SanBay selTu = (model.SanBay) cbTu.getSelectedItem();
                model.SanBay selDen = (model.SanBay) cbDen.getSelectedItem();
                capNhatHaiComboBox(cbTu, cbDen, selTu, selDen);
            }
        };
        cbTu.addItemListener(listener);
        cbDen.addItemListener(listener);

        // Sự kiện nút Đổi chiều (Truyền chéo giá trị cho nhau)
        btnSwap.addActionListener(e -> {
            if (isUpdatingCombo) return;
            model.SanBay selTu = (model.SanBay) cbTu.getSelectedItem();
            model.SanBay selDen = (model.SanBay) cbDen.getSelectedItem();
            capNhatHaiComboBox(cbTu, cbDen, selDen, selTu); // Tráo đổi vị trí
        });
    }

    private void capNhatHaiComboBox(javax.swing.JComboBox cbTu, javax.swing.JComboBox cbDen, model.SanBay selTu, model.SanBay selDen) {
        isUpdatingCombo = true;
        
        // 1. Cập nhật ô TỪ (Giấu sân bay đang nằm ở ô ĐẾN)
        cbTu.removeAllItems();
        cbTu.addItem(new model.SanBay("", "", "", "Chọn thành phố"));
        for (model.SanBay sb : danhSachSanBayGoc) {
            if (selDen == null || selDen.getMaSanBay().isEmpty() || !sb.getMaSanBay().equals(selDen.getMaSanBay())) {
                cbTu.addItem(sb);
            }
        }
        setComboSelection(cbTu, selTu);
        
        // 2. Cập nhật ô ĐẾN (Giấu sân bay đang nằm ở ô TỪ)
        cbDen.removeAllItems();
        cbDen.addItem(new model.SanBay("", "", "", "Chọn thành phố"));
        for (model.SanBay sb : danhSachSanBayGoc) {
            if (selTu == null || selTu.getMaSanBay().isEmpty() || !sb.getMaSanBay().equals(selTu.getMaSanBay())) {
                cbDen.addItem(sb);
            }
        }
        setComboSelection(cbDen, selDen);
        
        isUpdatingCombo = false;
    }

    private void setComboSelection(javax.swing.JComboBox cb, model.SanBay target) {
        if (target == null || target.getMaSanBay().isEmpty()) { cb.setSelectedIndex(0); return; }
        for (int i = 0; i < cb.getItemCount(); i++) {
            model.SanBay item = (model.SanBay) cb.getItemAt(i);
            if (item.getMaSanBay().equals(target.getMaSanBay())) {
                cb.setSelectedIndex(i); return;
            }
        }
        cb.setSelectedIndex(0);
    }
    
    private void setupDatePicker(javax.swing.JTextField txtField) {
        txtField.setEditable(false); 
        txtField.setBackground(java.awt.Color.WHITE);
        txtField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtField.setText(java.time.LocalDate.now().format(dateFormatter));

        txtField.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (!txtField.isEnabled()) return; 
                hienThiLich(txtField);
            }
        });
    }

    private void hienThiLich(javax.swing.JTextField txtField) {
        try { currentMonth = java.time.LocalDate.parse(txtField.getText(), dateFormatter); } 
        catch (Exception ex) { currentMonth = java.time.LocalDate.now(); }

        javax.swing.JPopupMenu popup = new javax.swing.JPopupMenu();
        javax.swing.JPanel pnlMain = new javax.swing.JPanel(new java.awt.BorderLayout());
        pnlMain.setBackground(java.awt.Color.WHITE);
        pnlMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        
        javax.swing.JPanel pnlHeader = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 5));
        pnlHeader.setBackground(java.awt.Color.WHITE);
        
        javax.swing.JButton btnPrev = new javax.swing.JButton("<");
        javax.swing.JButton btnNext = new javax.swing.JButton(">");
        btnPrev.setFocusPainted(false); btnPrev.setBackground(java.awt.Color.WHITE);
        btnNext.setFocusPainted(false); btnNext.setBackground(java.awt.Color.WHITE);
        
        String[] months = {"Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"};
        javax.swing.JComboBox<String> cbMonth = new javax.swing.JComboBox<>(months);
        javax.swing.JSpinner spnYear = new javax.swing.JSpinner(new javax.swing.SpinnerNumberModel(currentMonth.getYear(), 2024, 2100, 1));
        spnYear.setEditor(new javax.swing.JSpinner.NumberEditor(spnYear, "#"));
        
        pnlHeader.add(btnPrev); pnlHeader.add(cbMonth); pnlHeader.add(spnYear); pnlHeader.add(btnNext);
        pnlMain.add(pnlHeader, java.awt.BorderLayout.NORTH);

        javax.swing.JPanel pnlDays = new javax.swing.JPanel(new java.awt.GridLayout(0, 7, 0, 0));
        pnlDays.setBackground(java.awt.Color.WHITE);
        String[] daysOfWeek = {"CN", "T2", "T3", "T4", "T5", "T6", "T7"};

        final boolean[] isUpdatingUI = {false};

        Runnable drawDays = () -> {
            pnlDays.removeAll();
            isUpdatingUI[0] = true;
            cbMonth.setSelectedIndex(currentMonth.getMonthValue() - 1);
            spnYear.setValue(currentMonth.getYear());
            isUpdatingUI[0] = false;

            for (String d : daysOfWeek) {
                javax.swing.JLabel lbl = new javax.swing.JLabel(d, javax.swing.SwingConstants.CENTER);
                lbl.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
                lbl.setForeground(java.awt.Color.GRAY);
                pnlDays.add(lbl);
            }
            
            java.time.LocalDate today = java.time.LocalDate.now();
            java.time.LocalDate minDate = today; 
            
            javax.swing.JTextField txtPhuThuoc = null;
            int soNgayCach = 0;

            if (txtField == jFormattedTextField2) {
                txtPhuThuoc = jFormattedTextField1; soNgayCach = 2;
            } else if (listNgayExtra.contains(txtField)) {
                int index = listNgayExtra.indexOf(txtField);
       
                txtPhuThuoc = (index == 0) ? null : listNgayExtra.get(index - 1);
                soNgayCach = (index == 0) ? 0 : 1;
            }

            if (txtPhuThuoc != null) {
                try {
                    minDate = java.time.LocalDate.parse(txtPhuThuoc.getText(), dateFormatter).plusDays(soNgayCach); 
                } catch (Exception ex) { minDate = today; }
            }

            int daysInMonth = currentMonth.lengthOfMonth();
            java.time.LocalDate prevMonthDate = currentMonth.minusMonths(1);
            java.time.LocalDate nextMonthDate = currentMonth.plusMonths(1);
            int startDay = currentMonth.withDayOfMonth(1).getDayOfWeek().getValue(); 
            if (startDay == 7) startDay = 0; 

            for (int i = 0; i < 42; i++) {
                java.time.LocalDate cellDate;
                boolean isCurrentMonth = false;

                if (i < startDay) {
                    cellDate = java.time.LocalDate.of(prevMonthDate.getYear(), prevMonthDate.getMonthValue(), prevMonthDate.lengthOfMonth() - startDay + 1 + i);
                } else if (i < startDay + daysInMonth) {
                    cellDate = java.time.LocalDate.of(currentMonth.getYear(), currentMonth.getMonthValue(), i - startDay + 1);
                    isCurrentMonth = true;
                } else {
                    cellDate = java.time.LocalDate.of(nextMonthDate.getYear(), nextMonthDate.getMonthValue(), i - (startDay + daysInMonth) + 1);
                }

                javax.swing.JButton btnDay = new javax.swing.JButton(String.valueOf(cellDate.getDayOfMonth()));
                btnDay.setMargin(new java.awt.Insets(5, 5, 5, 5));
                btnDay.setFocusPainted(false); btnDay.setBorderPainted(false);
                btnDay.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 13));
                
                if (cellDate.isBefore(minDate)) {
                    btnDay.setEnabled(false);
                    btnDay.setBackground(java.awt.Color.WHITE);
                    btnDay.setForeground(new java.awt.Color(220, 220, 220)); 
                } else {
                    if (!isCurrentMonth) {
                        btnDay.setForeground(new java.awt.Color(160, 160, 160));
                        btnDay.setBackground(new java.awt.Color(250, 250, 250));
                    } else if (cellDate.isEqual(today)) {
                        btnDay.setBackground(new java.awt.Color(220, 240, 255));
                        btnDay.setForeground(java.awt.Color.BLUE);
                        btnDay.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 13));
                    } else {
                        btnDay.setBackground(java.awt.Color.WHITE);
                        btnDay.setForeground(java.awt.Color.BLACK);
                    }
                    
                    btnDay.addActionListener(ev -> {
                        txtField.setText(cellDate.format(dateFormatter));
                        popup.setVisible(false); 
                        
                        if (txtField == jFormattedTextField1 && jCheckBox1.isSelected()) {
                            try {
                                java.time.LocalDate currentReturn = java.time.LocalDate.parse(jFormattedTextField2.getText(), dateFormatter);
                                if (currentReturn.isBefore(cellDate.plusDays(2))) jFormattedTextField2.setText(cellDate.plusDays(2).format(dateFormatter));
                            } catch (Exception ex) {}
                        } else {
                            int startIndex = (txtField == jFormattedTextField1) ? 0 : (listNgayExtra.indexOf(txtField) + 1);
                            if (startIndex >= 0) {
                                java.time.LocalDate prevDate = cellDate;
                                for (int k = startIndex; k < listNgayExtra.size(); k++) {
                                    javax.swing.JTextField txtSau = listNgayExtra.get(k);
                                    try {
                                        java.time.LocalDate dateSau = java.time.LocalDate.parse(txtSau.getText(), dateFormatter);
                                        if (dateSau.isBefore(prevDate.plusDays(1))) {
                                            prevDate = prevDate.plusDays(1);
                                            txtSau.setText(prevDate.format(dateFormatter));
                                        } else {
                                            prevDate = dateSau;
                                        }
                                    } catch (Exception ex) {}
                                }
                            }
                        }
                    });
                }
                pnlDays.add(btnDay);
            }
            pnlMain.revalidate(); pnlMain.repaint();
        };

        cbMonth.addActionListener(ev -> { if (!isUpdatingUI[0]) { currentMonth = currentMonth.withMonth(cbMonth.getSelectedIndex() + 1); drawDays.run(); }});
        spnYear.addChangeListener(ev -> { if (!isUpdatingUI[0]) { currentMonth = currentMonth.withYear((Integer) spnYear.getValue()); drawDays.run(); }});
        btnPrev.addActionListener(ev -> { currentMonth = currentMonth.minusMonths(1); drawDays.run(); });
        btnNext.addActionListener(ev -> { currentMonth = currentMonth.plusMonths(1); drawDays.run(); });

        drawDays.run();
        pnlMain.add(pnlDays, java.awt.BorderLayout.CENTER); popup.add(pnlMain);
        popup.show(txtField, 0, txtField.getHeight());
    }

    private void taoHangChuyenBayMoi() {
        if (listNgayExtra.size() >= 4) { 
            javax.swing.JOptionPane.showMessageDialog(this, "Chỉ được đặt tối đa 5 chuyến bay cùng lúc!");
            return;
        }

        javax.swing.JPanel pnlRow = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));
        pnlRow.setOpaque(false); 
        pnlRow.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 65));
        javax.swing.JComboBox cbTuEx = new javax.swing.JComboBox<>();
        javax.swing.JComboBox cbDenEx = new javax.swing.JComboBox<>();
        javax.swing.JFormattedTextField txtNgayEx = new javax.swing.JFormattedTextField();
        javax.swing.JButton btnXoa = new javax.swing.JButton("Xóa");
        javax.swing.JButton btnSwapEx = new javax.swing.JButton("<=>"); // NÚT SWAP MỚI

        cbTuEx.setPreferredSize(new java.awt.Dimension(232, 56));
        cbDenEx.setPreferredSize(new java.awt.Dimension(232, 56));
        txtNgayEx.setPreferredSize(new java.awt.Dimension(150, 56));
        btnXoa.setPreferredSize(new java.awt.Dimension(70, 56));
        

        btnSwapEx.setPreferredSize(new java.awt.Dimension(60, 56));
        btnSwapEx.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        try { btnSwapEx.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("svgmaterials/icons/bx-transfer.svg", 24, 24)); btnSwapEx.setText(""); } catch(Exception ex){}

        btnXoa.setBackground(new java.awt.Color(255, 100, 100));
        btnXoa.setForeground(java.awt.Color.WHITE);
        btnXoa.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));

        cbTuEx.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        cbDenEx.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        txtNgayEx.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));

        setupHoTroChonSanBay(cbTuEx, cbDenEx, btnSwapEx);
        setupDatePicker(txtNgayEx); 

        javax.swing.JTextField txtTruocDo = listNgayExtra.isEmpty() ? jFormattedTextField1 : listNgayExtra.get(listNgayExtra.size() - 1);
        try {
            java.time.LocalDate ngayTruoc = java.time.LocalDate.parse(txtTruocDo.getText(), dateFormatter);
            txtNgayEx.setText(ngayTruoc.plusDays(1).format(dateFormatter));
        } catch(Exception e) {}

        listNgayExtra.add(txtNgayEx);
        listBtnXoa.add(btnXoa);

        btnXoa.addActionListener(e -> {
            pnlMultiCities.remove(pnlRow);
            listNgayExtra.remove(txtNgayEx);
            listBtnXoa.remove(btnXoa);
            capNhatGiaoDienMultiCity(); 
        });

        javax.swing.JLabel lblTu = new javax.swing.JLabel("Từ");
        lblTu.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        javax.swing.JLabel lblDen = new javax.swing.JLabel("Đến");
        lblDen.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        javax.swing.JLabel lblNgay = new javax.swing.JLabel("Ngày đi");
        lblNgay.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));

        pnlRow.add(lblTu); pnlRow.add(cbTuEx);
        pnlRow.add(btnSwapEx); // Chèn nút Swap vào giữa
        pnlRow.add(lblDen); pnlRow.add(cbDenEx);
        pnlRow.add(lblNgay); pnlRow.add(txtNgayEx);
        pnlRow.add(btnXoa);

        pnlMultiCities.add(pnlRow, pnlMultiCities.getComponentCount() - 1);
        capNhatGiaoDienMultiCity();
    }

    private void capNhatGiaoDienMultiCity() {
        
        boolean hienNutXoa = listBtnXoa.size() > 2; 
        for (javax.swing.JButton btn : listBtnXoa) {
            btn.setVisible(hienNutXoa);
        }
        pnlMultiCities.revalidate();
        pnlMultiCities.repaint();
    } 

    private void setupLogo() {
        
        jLabel1.setText(""); 
        
        try {
            
            javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon("src/resources/images/logos.png");
            
            
            if (originalIcon.getIconWidth() > 0) {
                
                java.awt.Image scaledImg = originalIcon.getImage().getScaledInstance(-1, 100, java.awt.Image.SCALE_SMOOTH);
                jLabel1.setIcon(new javax.swing.ImageIcon(scaledImg));
            } else {
                System.out.println("Báo động: Không tìm thấy ảnh tại src/resources/images");
                jLabel1.setText("AirLiner");
            }
        } catch (Exception e) {
            System.out.println("Lỗi hiển thị logo: " + e.getMessage());
        }
    }


    private void setupBusinessLogic() {
        loadDanhSachSanBay();
        setupHoTroChonSanBay(cbCities, cbCities1, jButton2);

        btnGChuyenBay.add(jRadioButton1); 
        btnGChuyenBay.add(jRadioButton2);
        jRadioButton1.setSelected(true);

        pnlMultiCities.setLayout(new javax.swing.BoxLayout(pnlMultiCities, javax.swing.BoxLayout.Y_AXIS));
        pnlMultiCities.setVisible(false); 

    
        java.util.function.Consumer<Boolean> anHienHangGoc = (isHien) -> {
            jLabel2.setVisible(isHien);       // Chữ Từ
            jLabel3.setVisible(isHien);       // Chữ Đến
            cbCities.setVisible(isHien);      // Ô Từ
            jButton2.setVisible(isHien);      // Nút <=>
            cbCities1.setVisible(isHien);     // Ô Đến
            jLabel4.setVisible(isHien);       // Chữ Ngày đi
            jFormattedTextField1.setVisible(isHien); // Ô Ngày đi
            jCheckBox1.setVisible(isHien);    // Checkbox Khứ hồi
            jFormattedTextField2.setVisible(isHien); // Ô Ngày về
            jButton3.setVisible(isHien);      // NÚT TÌM KIẾM CŨ
        };


        javax.swing.JPanel pnlButtonWrapper = new javax.swing.JPanel(new java.awt.BorderLayout());
        pnlButtonWrapper.setOpaque(false);
        pnlButtonWrapper.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15)); // Căn lề 2 bên

        pnlButtonWrapper.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 65));
        
    
        pnlMultiCities.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, Integer.MAX_VALUE));

        btnMoreCities = new javax.swing.JButton("(+) Thêm chuyến bay khác");
        btnMoreCities.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        btnMoreCities.setPreferredSize(new java.awt.Dimension(250, 45));
        
    
        btnSearchMulti = new javax.swing.JButton("Tìm chuyến bay");
        btnSearchMulti.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        btnSearchMulti.setBackground(new java.awt.Color(255, 193, 7)); // ACCENT_COLOR
        btnSearchMulti.setForeground(new java.awt.Color(18, 32, 64));  // PRIMARY_COLOR
        btnSearchMulti.setForeground(java.awt.Color.WHITE);
        btnSearchMulti.setPreferredSize(new java.awt.Dimension(200, 50));
        
    
        pnlButtonWrapper.add(btnMoreCities, java.awt.BorderLayout.WEST);
        pnlButtonWrapper.add(btnSearchMulti, java.awt.BorderLayout.EAST);
   
        jRadioButton2.addActionListener(e -> {
            if(jRadioButton2.isSelected()) {
                anHienHangGoc.accept(false); 
                
                pnlMultiCities.removeAll(); 
                listNgayExtra.clear();
                listBtnXoa.clear();
                
         
                pnlMultiCities.setOpaque(true);
                pnlMultiCities.setBackground(jPanel3.getBackground());
                
                pnlMultiCities.add(pnlButtonWrapper);
                pnlMultiCities.setVisible(true);
                
    
                taoHangChuyenBayMoi(); 
                taoHangChuyenBayMoi(); 
            }
        });
        
        // SỰ KIỆN QUAY LẠI MỘT CHIỀU
        jRadioButton1.addActionListener(e -> {
            if(jRadioButton1.isSelected()) {
                anHienHangGoc.accept(true); // Trả lại hàng tĩnh
                jCheckBox1.setSelected(false);
                jFormattedTextField2.setEnabled(false);
                pnlMultiCities.setVisible(false);
            }
        });

        for (java.awt.event.ActionListener al : btnMoreCities.getActionListeners()) { btnMoreCities.removeActionListener(al); }
        btnMoreCities.addActionListener(e -> taoHangChuyenBayMoi());

        jCheckBox1.addActionListener(e -> {
            boolean isKhuHoi = jCheckBox1.isSelected();
            jFormattedTextField2.setEnabled(isKhuHoi); 
            if (isKhuHoi) {
                try {
                    java.time.LocalDate ngayDi = java.time.LocalDate.parse(jFormattedTextField1.getText(), dateFormatter);
                    jFormattedTextField2.setText(ngayDi.plusDays(2).format(dateFormatter));
                } catch (Exception ex) {}
            }
        });
    } 

   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            java.util.prefs.Preferences prefs = java.util.prefs.Preferences.userNodeForPackage(gui.DangNhapFrm.class);
            String savedUser = prefs.get("saved_user", null);
            String savedPass = prefs.get("saved_pass", null);
            
            if (savedUser != null && savedPass != null) {
                bll.NguoiDungBUS bus = new bll.NguoiDungBUS();
                model.NguoiDung nd = bus.checkLogin(savedUser, savedPass);
                if (nd != null) {
                    new MainFrame(nd).setVisible(true);
                    return;
                }
            }
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatCho;
    private javax.swing.JButton btnDiary;
    private javax.swing.ButtonGroup btnGChuyenBay;
    private javax.swing.JButton btnHanhKhach;
    private javax.swing.JButton btnKhuyenMai;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignin;
    private javax.swing.JButton btnVeMB;
    private javax.swing.JComboBox<String> cbCities;
    private javax.swing.JComboBox<String> cbCities1;
    private javax.swing.JComboBox<String> cbDonViTienTe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMenuHeader;
    private javax.swing.JPanel pnlMultiCities;
    // End of variables declaration//GEN-END:variables
}
