/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author DellU
 */
public class UserInfoFrm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserInfoFrm.class.getName());

    /**
     * Creates new form UserInfoFrm
     */
    public UserInfoFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginLable = new gui.custom.RoundedPanel();
        NameUser = new javax.swing.JTextField();
        LableUsername = new javax.swing.JLabel();
        LablePassword = new javax.swing.JLabel();
        btnGoogleAcc = new javax.swing.JButton();
        btnFacebookAcc = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        LableTitle = new javax.swing.JLabel();
        confirmPass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NameAccount = new javax.swing.JTextField();
        btnChangePassword = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PasswordField1 = new javax.swing.JPasswordField();
        btnBirth = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnAddress = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginLable.setBackground(new java.awt.Color(255, 255, 255));

        NameUser.addActionListener(this::NameUserActionPerformed);

        LableUsername.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        LableUsername.setText("Họ và tên:");

        LablePassword.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        LablePassword.setText("Password:");

        btnGoogleAcc.setBackground(new java.awt.Color(204, 204, 204));
        btnGoogleAcc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGoogleAcc.setText("Google");
        btnGoogleAcc.addActionListener(this::btnGoogleAccActionPerformed);

        btnFacebookAcc.setBackground(new java.awt.Color(204, 204, 204));
        btnFacebookAcc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFacebookAcc.setText("Facebook");
        btnFacebookAcc.addActionListener(this::btnFacebookAccActionPerformed);

        btnReturn.setText("Quay lại\n");

        btnExit.setText("Thoát");
        btnExit.addActionListener(this::btnExitActionPerformed);

        btnConfirm.setBackground(new java.awt.Color(255, 255, 51));
        btnConfirm.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnConfirm.setText("Đồng ý");

        LableTitle.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        LableTitle.setForeground(new java.awt.Color(255, 0, 0));
        LableTitle.setText("THÔNG TIN NGƯỜI DÙNG");

        confirmPass.setText("jPasswordField1");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Xác nhận password:");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Email/Số điện thoại: ");

        NameAccount.addActionListener(this::NameAccountActionPerformed);

        btnChangePassword.setBackground(new java.awt.Color(255, 255, 51));
        btnChangePassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnChangePassword.setText("Đổi Mật khẩu");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setText("Ngày sinh: ");

        PasswordField1.setText("jPasswordField1");

        btnBirth.setText("jButton2");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setText("Địa chỉ: ");

        btnAddress.setText("jButton2");

        javax.swing.GroupLayout LoginLableLayout = new javax.swing.GroupLayout(LoginLable);
        LoginLable.setLayout(LoginLableLayout);
        LoginLableLayout.setHorizontalGroup(
            LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLableLayout.createSequentialGroup()
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLableLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(LableTitle))
                    .addGroup(LoginLableLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginLableLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(btnChangePassword))
                    .addGroup(LoginLableLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginLableLayout.createSequentialGroup()
                                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGoogleAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFacebookAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(LoginLableLayout.createSequentialGroup()
                                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LablePassword)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(LableUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(49, 49, 49)
                                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        LoginLableLayout.setVerticalGroup(
            LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLableLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LableTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLableLayout.createSequentialGroup()
                        .addGap(0, 63, Short.MAX_VALUE)
                        .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btnBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(btnAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(LoginLableLayout.createSequentialGroup()
                        .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LableUsername)
                            .addComponent(NameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChangePassword)
                .addGap(18, 18, 18)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LablePassword))
                .addGap(18, 18, 18)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGoogleAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFacebookAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturn)
                    .addComponent(btnExit))
                .addGap(197, 197, 197))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(LoginLable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LoginLable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameUserActionPerformed

    private void btnGoogleAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoogleAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoogleAccActionPerformed

    private void btnFacebookAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacebookAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacebookAccActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void NameAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserInfoFrm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LablePassword;
    private javax.swing.JLabel LableTitle;
    private javax.swing.JLabel LableUsername;
    private javax.swing.JPanel LoginLable;
    private javax.swing.JTextField NameAccount;
    private javax.swing.JTextField NameUser;
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JButton btnAddress;
    private javax.swing.JButton btnBirth;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFacebookAcc;
    private javax.swing.JButton btnGoogleAcc;
    private javax.swing.JButton btnReturn;
    private javax.swing.JPasswordField confirmPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
